### PR TITLE
Upgrade to 2.2.1

### PR DESCRIPTION
**Pull request by alvarosanchez**
This fixes the compilation issue.

NOTE: the custom repo definition is temporary until JCenter syncs the latest version.

### CODE REVIEW

**Comment by pditommaso** [comment]
@tcrespog does this solve your test case?

**Comment by tcrespog** [comment]
Thanks for the PR @alvarosanchez.

@pditommaso, with this the project compiles, but the generated OpenAPI schema doesn't have the expected format. Bearing in mind the latest comments in https://github.com/micronaut-projects/micronaut-openapi/issues/313, I believe a fix is required in the Groovy language codebase in order to make it work as expected.

**Comment by alvarosanchez** [comment]
> Thanks for the PR @alvarosanchez.
> 
> @pditommaso, with this the project compiles, but the generated OpenAPI schema doesn't have the expected format. Bearing in mind the latest comments in [micronaut-projects/micronaut-openapi#313](https://github.com/micronaut-projects/micronaut-openapi/issues/313), I believe a fix is required in the Groovy language codebase in order to make it work as expected.

Correct, it's a bug in how Groovy parses the AST of classes from a JAR file.

**Comment by pditommaso** [comment]
Is the bug tracked in the Groovy Jira? If not it would make sense to open it.

**Pull request merged**
